### ISSUE TITLE
draft function WKRDBEST2 - subgroup 2: estimation object upper hierarchy

### ISSUE THREAD

**Issue by hgerritsen** [ices-eg/WK_RDBES#54]
First draft of the function doDBEestimantionObjUpp() which generates the DBE estimation object for the upper hierarchy tables

https://github.com/ices-eg/WK_RDBES/tree/master/WKRDB-EST2/subGroup2/funs/doDBEestimantionObjUpp.R

**Comment by rix133** [comment]
The discussion about it under #55
