### ISSUE TITLE
Include the function for mapColNamesFieldR directly in script

### ISSUE THREAD

**Issue by KirstenBirchHaakansson** [ices-eg/WK_RDBES#70]
The embedded map should run directly on https://github.com/ices-tools-dev/RDBES/blob/master/Documents/RDBES%20Data%20Model.xlsx

Code for the present map can be found in https://github.com/ices-eg/WK_RDBES/blob/master/WKRDB-EST2/testData/mapColNames.R

**Comment by davidcurrie2001** [comment]
I've included it in the "Data" directory of the draft project. The script to create it can be included in data-raw (I think).

**Comment by davidcurrie2001** [comment]
Code added to data-raw (based on @KirstenBirchHaakansson 's code) - output is saved to data directory
