### ISSUE TITLE
To Do list createRDBESraw [SG1]

### ISSUE THREAD

**Issue by nmprista** [ices-eg/WK_RDBES#83]
* [x] add the stop and warning messages to the user
* [x] add some checks
* [ ] should we add some data quality checking? E.g. if there is the same numTotal and numSamp within one cluster
* [x] make the script independent on files naming

**Comment by davidcurrie2001** [comment]
Anything apart from basic checks should be done when creating a "prep" object - the "raw" object should just be a copy of the RDBES data.

**Comment by davidcurrie2001** [comment]
Ok, you can now also pass in the file names as a parameters - otheriwse it will use the default names that the RDBES download provides

**Comment by davidcurrie2001** [comment]
The following script can be used to see the functions working:
````
# Load H1 data
myH1RawObject <- createRDBESRawObject(rdbesExtractPath = "tests\\testthat\\h1_v_1_19")
# Check the object created is ok (should return TRUE)
checkRDBESRawObject(myH1RawObject)

# Load H5 data
myH5RawObject <- createRDBESRawObject(rdbesExtractPath = "tests\\testthat\\h5_v_1_19")
# Check the object created is ok (should return TRUE)
checkRDBESRawObject(myH5RawObject)

# Combine our H1 and H5 objects
myCombinedRawObject <- combineRDBESRawObjects(rdbesRawObject1=myH1RawObject,
                                              rdbesRawObject2=myH5RawObject)
# Check the object created is ok (should return TRUE)
checkRDBESRawObject(myCombinedRawObject)
```
